import sys, io

def readfile (fn):
	with io.open(fn, 'r') as fp:
		return '"# {}\n{}\n"'.format( fn, fp.read().strip())

def readall (l):
	return '\n'.join(sanitize(readfile(f)) for f in sorted(l))

def sanitize (s):
	return s.strip().replace('\r', '').replace('\n', '\\n"\n"')

print(''.join([
	'// Auto-generated by fileToStr.py, do not edit !\n',
	'static const char ',
	sys.argv[1],
	'[] = \n',
	readall(sys.argv[2:]),
	'\n;'
]))